name: Deploy
on:
  push:
    branches:
      - main

env:
  DEP_PATH: ./requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: aufdenpunkt/python-safety-check@v1.0.5

      # - name: Deploy
      #   env:
      #     HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      #     HEROKU_APP_NAME: "gdp-chatbot" # Rename this to the app of your Heroku app.
      #   run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main